version: '3.8'

services:
  trinetra-sandbox:
    build: .
    image: shreekumarshah/project-trinetra:latest
    container_name: trinetra-sandbox
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
